default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"]&.sub(/\/([^\/]+)$/, '/\1_development') %>

test:
  <<: *default
  url: <%= ENV["DATABASE_URL"]&.sub(/\/([^\/]+)$/, '/\1_test') %>

production:
  primary:
    <<: *default
  cache:
    <<: *default
    database: <%= ENV["DATABASE_URL"]&.sub(/\/[^\/]+$/, "/cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV["DATABASE_URL"]&.sub(/\/[^\/]+$/, "/queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV["DATABASE_URL"]&.sub(/\/[^\/]+$/, "/cable") %>
    migrations_paths: db/cable_migrate
